function [iRg,iL1,iC1,iL2,iC2,iRl,vRl,vRg,vC1,vR1,vR2] = circuit_2coil_num5v2(ug,Rg,C1,L1,R1,M,L2,R2,C2,Rl,f)
%CIRCUIT_2COIL_NUM5V2
%    [IRG,IL1,IC1,IL2,IC2,IRL,VRL,VRG,VC1,VR1,VR2] = CIRCUIT_2COIL_NUM5V2(UG,RG,C1,L1,R1,M,L2,R2,C2,RL,F)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Mar-2015 09:49:51

t2 = pi.^2;
t3 = f.^2;
t4 = M.^2;
t5 = t2.^2;
t6 = t3.^2;
t7 = R1.*R2;
t8 = R2.*Rg;
t9 = R1.*Rl;
t10 = Rg.*Rl;
t11 = t2.*t3.*t4.*4.0;
t12 = L1.*pi.*R2.*f.*2.0i;
t13 = L2.*pi.*R1.*f.*2.0i;
t14 = L2.*pi.*Rg.*f.*2.0i;
t15 = L1.*pi.*Rl.*f.*2.0i;
t16 = C1.*pi.*Rg.*f.*t2.*t3.*t4.*8.0i;
t17 = C2.*pi.*Rl.*f.*t2.*t3.*t4.*8.0i;
t18 = C1.*L1.*L2.*pi.*Rg.*f.*t2.*t3.*-8.0i;
t19 = C2.*L1.*L2.*pi.*Rl.*f.*t2.*t3.*-8.0i;
t20 = C1.*pi.*R1.*R2.*Rg.*f.*2.0i;
t21 = C2.*pi.*R1.*R2.*Rl.*f.*2.0i;
t22 = C1.*pi.*R1.*Rg.*Rl.*f.*2.0i;
t23 = C2.*pi.*R2.*Rg.*Rl.*f.*2.0i;
t24 = C1.*C2.*L1.*L2.*Rg.*Rl.*t5.*t6.*1.6e1;
t25 = C1.*C2.*L1.*pi.*R2.*Rg.*Rl.*f.*t2.*t3.*-8.0i;
t26 = C1.*C2.*L2.*pi.*R1.*Rg.*Rl.*f.*t2.*t3.*-8.0i;
t41 = L1.*L2.*t2.*t3.*4.0;
t42 = C1.*L1.*R2.*Rg.*t2.*t3.*4.0;
t43 = C1.*L2.*R1.*Rg.*t2.*t3.*4.0;
t44 = C2.*L1.*R2.*Rl.*t2.*t3.*4.0;
t45 = C2.*L2.*R1.*Rl.*t2.*t3.*4.0;
t46 = C1.*L1.*Rg.*Rl.*t2.*t3.*4.0;
t47 = C2.*L2.*Rg.*Rl.*t2.*t3.*4.0;
t48 = C1.*C2.*Rg.*Rl.*t4.*t5.*t6.*1.6e1;
t49 = C1.*C2.*R1.*R2.*Rg.*Rl.*t2.*t3.*4.0;
t27 = t7+t8+t9+t10+t11+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t22+t23+t24+t25+t26-t41-t42-t43-t44-t45-t46-t47-t48-t49;
t28 = 1.0./t27;
t29 = R1.*R2.*-1i;
t30 = R1.*Rl.*-1i;
t31 = t2.*t3.*t4.*-4.0i;
t32 = L1.*L2.*t2.*t3.*4.0i;
t33 = L1.*pi.*R2.*f.*2.0;
t34 = L2.*pi.*R1.*f.*2.0;
t35 = L1.*pi.*Rl.*f.*2.0;
t36 = C2.*pi.*Rl.*f.*t2.*t3.*t4.*8.0;
t37 = C2.*L1.*R2.*Rl.*t2.*t3.*4.0i;
t38 = C2.*L2.*R1.*Rl.*t2.*t3.*4.0i;
t39 = C2.*pi.*R1.*R2.*Rl.*f.*2.0;
t50 = C2.*L1.*L2.*pi.*Rl.*f.*t2.*t3.*8.0;
t40 = t29+t30+t31+t32+t33+t34+t35+t36+t37+t38+t39-t50;
t51 = R2.*Rg.*-1i;
t52 = Rg.*Rl.*-1i;
t53 = L2.*pi.*Rg.*f.*2.0;
t54 = C1.*pi.*Rg.*f.*t2.*t3.*t4.*8.0;
t55 = C1.*L1.*R2.*Rg.*t2.*t3.*4.0i;
t56 = C1.*L2.*R1.*Rg.*t2.*t3.*4.0i;
t57 = C1.*L1.*Rg.*Rl.*t2.*t3.*4.0i;
t58 = C2.*L2.*Rg.*Rl.*t2.*t3.*4.0i;
t59 = C1.*pi.*R1.*R2.*Rg.*f.*2.0;
t60 = C1.*pi.*R1.*Rg.*Rl.*f.*2.0;
t61 = C2.*pi.*R2.*Rg.*Rl.*f.*2.0;
t62 = C1.*C2.*Rg.*Rl.*t4.*t5.*t6.*1.6e1i;
t63 = C1.*C2.*L1.*L2.*Rg.*Rl.*t5.*t6.*-1.6e1i;
t64 = C1.*C2.*R1.*R2.*Rg.*Rl.*t2.*t3.*4.0i;
t67 = C1.*L1.*L2.*pi.*Rg.*f.*t2.*t3.*8.0;
t68 = C1.*C2.*L1.*pi.*R2.*Rg.*Rl.*f.*t2.*t3.*8.0;
t69 = C1.*C2.*L2.*pi.*R1.*Rg.*Rl.*f.*t2.*t3.*8.0;
t65 = t29+t30+t31+t32+t33+t34+t35+t36+t37+t38+t39-t50+t51+t52+t53+t54+t55+t56+t57+t58+t59+t60+t61+t62+t63+t64-t67-t68-t69;
t66 = 1.0./t65;
t72 = t28.*t40.*ug.*1i;
t70 = -t72;
t71 = t70+ug;
iRg = -t71./Rg;
if nargout > 1
    t73 = L2.*pi.*f.*2.0i;
    t74 = C2.*pi.*R2.*Rl.*f.*2.0i;
    t75 = R2+Rl+t73+t74-C2.*L2.*Rl.*t2.*t3.*4.0;
    iL1 = t28.*t75.*ug;
end
if nargout > 2
    iC1 = C1.*pi.*f.*t28.*t40.*ug.*-2.0;
end
if nargout > 3
    t76 = C2.*pi.*Rl.*f.*2.0;
    t77 = t76-1i;
    iL2 = M.*pi.*f.*t28.*t77.*ug.*2.0;
end
if nargout > 4
    iC2 = C2.*M.*Rl.*t2.*t3.*t66.*ug.*4.0i;
end
if nargout > 5
    iRl = M.*pi.*f.*t66.*ug.*2.0;
end
if nargout > 6
    vRl = M.*pi.*Rl.*f.*t66.*ug.*2.0;
end
if nargout > 7
    vRg = t71;
end
if nargout > 8
    vC1 = t72;
end
if nargout > 9
    vR1 = R1.*t28.*t75.*ug;
end
if nargout > 10
    vR2 = M.*pi.*R2.*f.*t28.*t77.*ug.*2.0;
end
