function [amp_B1,amp_B2,amp_B1plusB2] = field_amplitude_2coil(B1_x,B1_y,B1_z,B2_x,B2_y,B2_z,iL1,iL2)
%FIELD_AMPLITUDE_2COIL
%    [AMP_B1,AMP_B2,AMP_B1PLUSB2] = FIELD_AMPLITUDE_2COIL(B1_X,B1_Y,B1_Z,B2_X,B2_Y,B2_Z,IL1,IL2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Mar-2015 10:01:33

t8 = B1_x.*iL1;
t2 = abs(t8);
t11 = B1_y.*iL1;
t3 = abs(t11);
t14 = B1_z.*iL1;
t4 = abs(t14);
amp_B1 = sqrt(t2.^2+t3.^2+t4.^2);
if nargout > 1
    t9 = B2_x.*iL2;
    t5 = abs(t9);
    t12 = B2_y.*iL2;
    t6 = abs(t12);
    t15 = B2_z.*iL2;
    t7 = abs(t15);
    amp_B2 = sqrt(t5.^2+t6.^2+t7.^2);
end
if nargout > 2
    t10 = abs(t8+t9);
    t13 = abs(t11+t12);
    t16 = abs(t14+t15);
    amp_B1plusB2 = sqrt(t10.^2+t13.^2+t16.^2);
end
