%% Generates 2-coil system struct with resistance and capacitance calculations.

CoilDesc = struct();
CoilDesc.structName = 'elliptic_two_coils_model';
CoilDesc.functionName = {'elliptic_two_coils_resistance', 'elliptic_two_coils_inductance'};
CoilDesc.functionSupportArrayInput = [true, false];
CoilDesc.inputParameter = {{},...
  {'f','c1nr', 'c1nz', 'c1dr', 'c1r0', 'c1a', 'c1sigma', 'c1wire',...
  'c2nr', 'c2nz', 'c2dr', 'c2r0', 'c2a', 'c2sigma', 'c2wire'},...
  {'c1nr', 'c1nz', 'c1r0', 'c1z0', 'c1dr', 'c1dz', 'c1a',...
  'c2nr', 'c2nz', 'c2r0', 'c2z0', 'c2dr', 'c2dz', 'c2a'}};
CoilDesc.inputValue = {{},...
  {85e3, 5, 5, 1e-2, 7e-2, 3e-3, 5.8e7, 's',...
  5, 5, 1e-2, 7e-2, 3e-3, 5.8e7, 's'},...
  {5, 5, 7e-2, -4e-2, 1e-2, 1e-2, 3e-3,...
  5, 5, 7e-2, 3e-1, 1e-2, 1e-2, 3e-3}};
CoilDesc.outputParameter = {{'R1', 'R2'}, {'L1', 'L2', 'M'}};
CoilDesc.outputValue = {{nan, nan}, {nan, nan, nan}};

save([pwd,'\model_struct\coil\elliptic_two_coil\', CoilDesc.structName], '-struct', 'CoilDesc');