function [B1_x,B1_y,B1_z,B2_x,B2_y,B2_z] = analyt_collapsed_2coil_Bfield(N1,N2,d,a1,a2,b,sigma,X,Y,Z)
%ANALYT_COLLAPSED_2COIL_BFIELD
%    [B1_X,B1_Y,B1_Z,B2_X,B2_Y,B2_Z] = ANALYT_COLLAPSED_2COIL_BFIELD(N1,N2,D,A1,A2,B,SIGMA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Mar-2015 08:35:45

t2 = a1.^2;
t3 = X.^2;
t4 = Y.^2;
t5 = Z.^2;
t6 = t3+t4+t5;
t7 = 1.0./t6.^(5.0./2.0);
B1_x = N1.*pi.*X.*Z.*t2.*t7.*3.0e-7;
if nargout > 1
    B1_y = N1.*pi.*Y.*Z.*t2.*t7.*3.0e-7;
end
if nargout > 2
    B1_z = N1.*pi.*t2.*1.0./t6.^(3.0./2.0).*(-1.0e-7)+N1.*pi.*t2.*t5.*t7.*3.0e-7;
end
if nargout > 3
    t8 = Z-d;
    t9 = a2.^2;
    t10 = t8.^2;
    t11 = t3+t4+t10;
    t12 = 1.0./t11.^(5.0./2.0);
    B2_x = N2.*pi.*X.*t8.*t9.*t12.*3.0e-7;
end
if nargout > 4
    B2_y = N2.*pi.*Y.*t8.*t9.*t12.*3.0e-7;
end
if nargout > 5
    B2_z = N2.*pi.*t9.*1.0./t11.^(3.0./2.0).*(-1.0e-7)+N2.*pi.*t9.*t10.*t12.*3.0e-7;
end
