function [L1,L2,M,R1,R2] = analyt_collapsed_2coil(N1,N2,d,a1,a2,b,sigma)
%ANALYT_COLLAPSED_2COIL
%    [L1,L2,M,R1,R2] = ANALYT_COLLAPSED_2COIL(N1,N2,D,A1,A2,B,SIGMA)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Mar-2015 08:32:12

t2 = 1.0./b;
L1 = N1.^2.*pi.*a1.*(log(a1.*t2.*8.0)-7.0./4.0).*4.0e-7;
if nargout > 1
    L2 = N2.^2.*pi.*a2.*(log(a2.*t2.*8.0)-7.0./4.0).*4.0e-7;
end
if nargout > 2
    t3 = a1+a2;
    t4 = t3.^2;
    t5 = d.^2;
    t6 = t4+t5;
    t7 = sqrt(a1);
    t8 = sqrt(a2);
    t9 = 1.0./sqrt(a1);
    t10 = 1.0./sqrt(a2);
    t11 = 1.0./t6;
    t12 = a1.*a2.*t11.*4.0;
    t13 = sqrt(t6);
    [K, E] = ellipke(t12);
%     M = N1.*N2.*pi.*t7.*t8.*(ellipticK(t12).*(1.0./sqrt(t6).*t7.*t8.*2.0-t9.*t10.*t13)+t9.*t10.*t13.*ellipticE(t12)).*(-4.0e-7);
    M = N1.*N2.*pi.*t7.*t8.*(K.*(1.0./sqrt(t6).*t7.*t8.*2.0-t9.*t10.*t13)+t9.*t10.*t13.*E).*(-4.0e-7);
end
if nargout > 3
    t14 = 1.0./b.^2;
    t15 = 1.0./sigma;
    R1 = N1.*a1.*t14.*t15.*2.0;
end
if nargout > 4
    R2 = N2.*a2.*t14.*t15.*2.0;
end
